version:
  1
formatters:
  simple:
    format: '[%(asctime)s] (%(filename)20s:%(lineno)4s) [%(levelname)8s] - %(message)s '
    datefmt: '%Y-%m-%d %H:%M:%S'
  complex:
    format: '[%(asctime)s] (%(filename)20s:%(lineno)4s) [%(levelname)8s] - %(message)s '
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: complex
    filename: ./files/example.debug.log
    mode: a
    maxBytes: 8388608
    backupCount: 10
  error:
    class: logging.FileHandler
    level: ERROR
    formatter: complex
    filename: ./files/example.error.log
    mode: a
  email:
    class: logging.handlers.SMTPHandler
    level: ERROR
    formatter: complex
    mailhost: 
      - smtp.comcast.net
      - 25 
    fromaddr: southfork.scherer@comcast.net
    toaddrs: jscherer26@gmail.com
    subject: Southfork Alarm Notice
    credentials: 
      - southfork.scherer
      - Cc11012003
    secure: True
  history:
    class: logging.handlers.HistoryHandler
    level: DEBUG
    formatter: complex
    capacity: 15
    flushLevel: ERROR
    target: error
  memory:
    class: logging.handlers.MemoryHandler
    level: DEBUG
    formatter: complex
    capacity: 25
    flushLevel: ERROR
    target: error
loggers:
  err:
    level: ERROR
    handlers: [error, ]
root:
  level: NOTSET
  handlers: [debug, email, history]