version:
  1
formatters:
  complex:
    format: '[%(asctime)s] (%(filename)20s:%(lineno)4s) [%(levelname)8s] - %(message)s '
handlers:
  error:
    class: logging.FileHandler
    formatter: complex
    level: ERROR
    filename: ./files/example.error.log
    mode: a
  history:
    class: logging.handlers.HistoryHandler
    formatter: complex
    level: DEBUG
    flushLevel: ERROR
    target: error
    capacity: 15
loggers:
  root:
    level: NOTSET
    handlers: [history]